#define RPR_DEBUG 0
#define RPR_LOG_VOLUME 0
#define RPR_COND_NUM 0
#define RPR_OUTPUT_CSV 1

#define RPR_DOM_INFLATION 0
#define RPR_TAKE_INFLATED_BOX 0
#define RPR_CENTERED_FORM 1
#define RPR_CYCLIC_X3 0
#define RPR_VALIDATE_CONNECTION 0

#define RPX_PROJ 1
